server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/avocado?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.avcado.entity

logging:
  level:
    com.xyc.springboot.dao : debug

